spring:
  application:
    name: super-market-loyalty-system
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
server:
  port: 8080
  servlet:
    context-path: /lcs-service

