spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: test
    driverClassName: org.h2.Driver
    initialize-schema: "always"
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

    h2:
      console:
        enabled: true

